/** 原生菜单点击后由后端 emit 到前端的事件名 */
export const MENU_EVENT = {
  new: 'menu://new',
  open: 'menu://open',
  openFolder: 'menu://open-folder',
  openRecent: 'menu://open-recent',
  clearRecent: 'menu://clear-recent',
  save: 'menu://save',
  saveAs: 'menu://save-as',
  closeTab: 'menu://close-tab',
  exportHtml: 'menu://export-html',
  exportHtmlPlain: 'menu://export-html-plain',
  exportPdf: 'menu://export-pdf',
  exportDocx: 'menu://export-docx',
  import: 'menu://import',
  openQuickly: 'menu://open-quickly',
  print: 'menu://print',
  spellCheck: 'menu://spell-check',
  help: 'menu://help',
  helpReadme: 'menu://help-readme',
  theme: 'menu://theme',
  settings: 'menu://settings',
  find: 'menu://find',
  replace: 'menu://replace',
  copyMarkdown: 'menu://copy-markdown',
  copyHtml: 'menu://copy-html',
  copyWord: 'menu://copy-word',
  pastePlain: 'menu://paste-plain',
  selectAll: 'menu://select-all',
  smartPunctuation: 'menu://smart-punctuation',
  heading1: 'menu://heading-1',
  heading2: 'menu://heading-2',
  heading3: 'menu://heading-3',
  heading4: 'menu://heading-4',
  heading5: 'menu://heading-5',
  heading6: 'menu://heading-6',
  paragraph: 'menu://paragraph',
  headingInc: 'menu://heading-inc',
  headingDec: 'menu://heading-dec',
  quote: 'menu://quote',
  orderedList: 'menu://ordered-list',
  bulletList: 'menu://bullet-list',
  taskList: 'menu://task-list',
  codeBlock: 'menu://code-block',
  mathBlock: 'menu://math-block',
  mathInline: 'menu://math-inline',
  horizontalRule: 'menu://horizontal-rule',
  insertTable: 'menu://insert-table',
  insertToc: 'menu://insert-toc',
  insertYaml: 'menu://insert-yaml',
  insertFootnote: 'menu://insert-footnote',
  sourceMode: 'menu://source-mode',
  focusMode: 'menu://focus-mode',
  typewriterMode: 'menu://typewriter-mode',
  bold: 'menu://bold',
  italic: 'menu://italic',
  underline: 'menu://underline',
  code: 'menu://code',
  strike: 'menu://strike',
  highlight: 'menu://highlight',
  subscript: 'menu://subscript',
  superscript: 'menu://superscript',
  link: 'menu://link',
  image: 'menu://image',
  clearFormat: 'menu://clear-format',
  toggleOutline: 'menu://toggle-outline',
  toggleFileTree: 'menu://toggle-file-tree',
  jumpTop: 'menu://jump-top',
  jumpBottom: 'menu://jump-bottom',
  indent: 'menu://indent',
  outdent: 'menu://outdent',
  alwaysOnTop: 'menu://always-on-top',
  unsupported: 'menu://unsupported',
} as const;

export type MenuEventName = (typeof MENU_EVENT)[keyof typeof MENU_EVENT];

/** 菜单项 id → 事件名 */
export function menuEventId(id: string): `menu://${string}` {
  return `menu://${id}`;
}
